name: build

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJECT_NAME: ${{ github.event.repository.name }}
  PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}

jobs:
  build:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
    - name: Checkout this repo with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Environment
      run: |
        New-Item -ItemType Directory -Force -Path ${{ env.PROJECT_RELEASE_PATH }}
        ls

    - name: Build awaaz
      run: |
        & "C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\Launch-VsDevShell.ps1" && ./build.ps1

    - name: Generate Artifacts
      run: |
        ls build/
        cp build/awaaz.exe ${{ env.PROJECT_RELEASE_PATH }}/awaaz.exe
        ls ${{ env.PROJECT_RELEASE_PATH }}/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}
        path: ${{ env.PROJECT_RELEASE_PATH }}/
